environment:
  matrix:
    - nodejs_version: "7"
    
matrix:
  fast_finish: true
  
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm install -g bower
  - npm install -g @angular/cli
  - npm install -g lite-server
  - npm install
    
test_script:
  - node --version
  - ng --version
  
build: on

cache:
  - node_modules
